name: gpl-reproduction
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - backcall=0.2.0=pyhd3eb1b0_0
  - ca-certificates=2021.10.26=h06a4308_2
  - certifi=2020.6.20=pyhd3eb1b0_3
  - decorator=5.1.1=pyhd3eb1b0_0
  - ipython=7.16.1=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.17.0=py36_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - ncurses=6.3=h7f8727e_2
  - openssl=1.1.1l=h7f8727e_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.2.2=py36h06a4308_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pygments=2.11.2=pyhd3eb1b0_0
  - python=3.6.13=h12debd9_1
  - readline=8.1=h27cfd23_0
  - setuptools=58.0.4=py36h06a4308_0
  - sqlite=3.37.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - traitlets=4.3.3=py36h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7f8727e_4
  - pip:
    - absl-py==0.15.0
    - astunparse==1.6.3
    - beir==0.2.3
    - cached-property==1.5.2
    - cachetools==4.2.4
    - clang==5.0
    - click==8.0.3
    - crash-ipdb==0.0.3
    - dataclasses==0.8
    - easy-elasticsearch==0.0.7
    - elasticsearch==7.12.1
    - faiss-cpu==1.7.1.post3
    - filelock==3.4.1
    - flatbuffers==1.12
    - gast==0.4.0
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.43.0
    - h5py==3.1.0
    - huggingface-hub==0.2.1
    - ipdb==0.13.9
    - joblib==1.1.0
    - keras==2.6.0
    - keras-preprocessing==1.1.2
    - markdown==3.3.6
    - nltk==3.6.7
    - numpy==1.19.5
    - oauthlib==3.1.1
    - opt-einsum==3.3.0
    - pillow==8.4.0
    - protobuf==3.19.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pytrec-eval==0.5
    - pyyaml==6.0
    - regex==2021.11.10
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - sacremoses==0.0.46
    - scikit-learn==0.24.2
    - scipy==1.5.4
    - sentence-transformers==2.1.0
    - sentencepiece==0.1.96
    - six==1.15.0
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.6.2
    - tensorflow-estimator==2.6.0
    - tensorflow-hub==0.12.0
    - tensorflow-text==2.6.0
    - termcolor==1.1.0
    - threadpoolctl==3.0.0
    - tokenizers==0.10.3
    - toml==0.10.2
    - torch==1.10.1
    - torchvision==0.11.2
    - transformers==4.15.0
    - typing-extensions==3.7.4.3
    - werkzeug==2.0.2
    - wrapt==1.12.1
prefix: /home/ukp/anaconda3/envs/gpl-reproduction
